apiVersion: v1
kind: Pod
metadata:
  name: print-config-pod
spec:
  containers:
    - name: print-container
      image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "===== application.json =====";
          cat /etc/config/application.json;
          echo "===== Secret Value =====";
          echo $DB_PASSWORD;
          sleep 3600
      env:
        - name: DB_PASSWORD
          value: "{{ .Values.app.secret.db_password }}"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: app-config
